name: CD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.LOBOT_TOKEN }}

      - name: build zero-dependency docs
        shell: bash
        run: |
          set -x
          npm i redoc-cli --save-dev && npx patch-package
          npm run redoc

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: push builds to `deployment`
        shell: bash
        run: |
          set -x
          git config user.name lobot
          git config user.email lobot@lob.com
          git update-index -q --refresh
          git add --force docs/index.html
          git commit -m "pushing builds" --no-verify
          git push --force origin ${{ steps.extract_branch.outputs.branch }}:deployment
